title: arcadies
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5039417394436896
  brandStrength: 0
  rhythmicContrast: 0.05835505807772279
  brandColors:
    - '#ffffff'
    - '#2c2b30'
    - '#ad1c1f'
    - '#b9a582'
    - '#7a6844'
  lightness: 0.6866727322340012
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: arcadies.co.za
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7275985
layout_spectrum: 1
