title: arcadies
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5039417394436896
  brandStrength: 0.7060932
  rhythmicContrast: 0.05835505807772279
  brandColors:
    - '#171614'
    - '#E0E9F3'
    - '#B49887'
    - '#5C667F'
    - '#B3774C'
  lightness: 0.6866727322340012
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: arcadies.co.za
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7275985
layout_spectrum: 0.5591398
